name: avi-backend
region: nyc
services:
  - name: api
    # Use Dockerfile for build
    dockerfile_path: Dockerfile
    source_dir: /
    github:
      branch: main
      deploy_on_push: true
      repo: davodey/avi-backend

    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # HTTP port configuration
    http_port: 5055

    # Environment variables
    envs:
      - key: PORT
        value: "5055"
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: YTDLP_COOKIES_FILE
        value: "./cookies.txt"
        scope: RUN_TIME

    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs

    # Routes
    routes:
      - path: /
